# Network Science Exam (Part I)
---
<font color="darkblue"><b>INSTRUCTION</b></font>: In this exam, you may open your notes and use the notebooks released in class, but make sure you **cite your sources**, especially if you use code written by someone else. Although this is an open-notes exam, you are **not allowed to communicate and discuss with anyone** (especially not your classmates/LT-mates) while taking this exam. You are not to use any of these communication platforms (e.g. Discord, MS Teams, Signal, Telegram, Facebook, email, etc.) while taking the exam. If you have questions/clarifications about the exam, please message the instructor immediately (or any of the program staff members) via Zoom chat. Reminding everyone that AIM does not condone academic cheating/dishonesty **in any form**. Cheating in this exam, in particular, may get you expelled from the Institute.

---


## A. Adjacency Matrices (**6 pts**)

Consider the figure below.

<img src="exam_network.png" width=500>

_You may use the code below to build your matrices. The form below is arbitrary. This is just to provide you with the LaTex code for writing matrices_

\begin{equation*}
\mathcal{A}_d = A_{m,n} = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
\vdots  & \vdots  & \ddots & \vdots  \\
a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
\end{pmatrix}
\end{equation*}

---


1. Write the adjacency matrix (in LaTeX markdown form), $\mathcal{A}_d$, for this directed graph. Please be explicit on directionality. (**1 pt**)

\begin{equation*}
\mathcal{A}_d = A_{m,n} = 
\begin{pmatrix}
{0} & {0} & {0} & {0} & {1} & {0} & {1} & {0} \\
{0} & {0} & {1} & {0} & {0} & {0} & {0} & {0} \\
{1} & {0} & {0} & {1} & {0} & {1} & {0} & {0} \\
{0} & {0} & {1} & {0} & {0} & {0} & {0} & {0} \\
{0} & {0} & {0} & {0} & {0} & {1} & {0} & {0} \\
{1} & {0} & {0} & {0} & {0} & {0} & {0} & {0} \\
{0} & {0} & {0} & {0} & {0} & {1} & {0} & {0} \\
{0} & {0} & {0} & {0} & {0} & {1} & {0} & {0} \\
\end{pmatrix}
\end{equation*}

2. Write the resulting adjancency matrix (in LaTeX markdown form), $\mathcal{A}_u$,  if this were an undirected graph. (**1 pt**) 

\begin{equation*}
\mathcal{A}_u = A_{m,n} = 
\begin{pmatrix}
{0} & {0} & {1} & {0} & {1} & {1} & {1} & {0} \\
{0} & {0} & {1} & {0} & {0} & {0} & {0} & {0} \\
{1} & {1} & {0} & {1} & {0} & {1} & {0} & {0} \\
{0} & {0} & {1} & {0} & {0} & {0} & {0} & {0} \\
{1} & {0} & {0} & {0} & {0} & {1} & {0} & {0} \\
{1} & {0} & {1} & {0} & {1} & {0} & {1} & {1} \\
{1} & {0} & {0} & {0} & {0} & {1} & {0} & {0} \\
{0} & {0} & {0} & {0} & {0} & {1} & {0} & {0} \\
\end{pmatrix}
\end{equation*}

3. Generalize the equation for obtaining the number of paths of length $p$ between all pairs of nodes in $\mathcal{A}_u$ (undirected). Describe each variable/component in the equation. (**2 pts**)

\begin{equation}
N_{i j}^{(p)}=\left[\mathcal{A}_u^{p}\right]_{i j}
\end{equation}
Where:

- $p$ - path length
- $i$ = first node
- $j$ = second node
- $N$ = total number of nodes in an undirected graph

4. Generate the resulting matrix that will tell us the number of paths of length 3 between any two nodes in $\mathcal{A}_u$. You may either write in markdown your solution, but you must compute for the final matrix, or show it in code. (**2 pts**)

In [4]:
import numpy as np
Au = [[0,0,1,0,1,1,1,0],
     [0,0,1,0,0,0,0,0],
     [1,1,0,1,0,1,0,0],
     [0,0,1,0,0,0,0,0],
     [1,0,0,0,0,1,0,0],
     [1,0,1,0,1,0,1,1],
     [1,0,0,0,0,1,0,0],
     [0,0,0,0,0,1,0,0]]


In [17]:
print('The resulting matrix for path length = 3 is: \n\n', 
      np.linalg.matrix_power(Au, 3))

The resulting matrix for path length = 3 is: 

 [[ 6  1  9  1  7  8  7  3]
 [ 1  0  4  0  2  1  2  1]
 [ 9  4  2  4  2 10  2  1]
 [ 1  0  4  0  2  1  2  1]
 [ 7  2  2  2  2  8  2  1]
 [ 8  1 10  1  8  6  8  5]
 [ 7  2  2  2  2  8  2  1]
 [ 3  1  1  1  1  5  1  0]]


## B. Generative Algorithms (**6 pts**)

5. Choose one from the three generative algorithms in the most recent assignment. 

(a) Describe the algorithm. (**2 pts**) 

In the hidden parameter model, the network to be worked on already has a predefined average $P_k$.
In creating the hidden parameter model:
1. Start by $N$ isolated nodes.
2. Attach to each node a hidden parameter that can come from $p(n)$ distribution or is provided by a certain sequence {$η_i$}
3. Draw the networks after connecting the nodes, representing realizations generated by the same hidden parameter sequence.

(b) What is the advantage of using your chosen network model? (**2 pts**) 

In a configuration model, nodes are presented with "stubs" that should be connected to other nodes and the resulting topology has different permutations based on these stubs. However, there  is a big possibility that these nodes can connect to themselves, aka "self-links". The hidden parameter model, though it somehow works the same way as the configuration model, instead of connecting nodes via stub assignment, it connects nodes via an expected degree described by:

\begin{equation}
p_{ij} = \frac{\eta_i \eta_j}{\sum_k \eta_k}
\end{equation}

where:
- $i$, $j$ are nodes
- $eta$ is the assigned probability to connect to the other node, aka "hidden parameter", and
- $k$ is the number of nodes.

So the connections are based on probabilities based from the hidden parameter.

(c) When is it most useful? Cite an example. (**2 pts**) 

It is useful for law enforcement when tracking down a certain criminal or a terrorist. Law officials can find possible links of criminals to less obvious people in the network and this can be used to trace where the criminal is hiding, as in the case of Bin Laden.

## C. Network Models (**12 pts**)

6. Provide and explain the expressions for the probability distribution $P(L)$, average number of links $<L>$ and mean degree $<k>$ of an undirected network generated using Erdös and Renyi’s (ER) model with $N$ nodes. (**6 pts**) If you are going to use additional variables, make sure they are properly defined. You may write the equations in LaTeX in the markdown cell below.



\begin{equation}
P(L)=\left(\begin{array}{c}
\left(\begin{array}{c}
N \\
2
\end{array}\right) \\
L
\end{array}\right) p^{L}(1-p)^{\frac{N(N-1)}{2}-L}
\end{equation}

P is the probability of node connection.   
L is number of links. 
N is the total number of nodes.

For values with bigger nodes:

\begin{equation}
p(l)=\exp ^{-<k>} \frac{<k>^{k}}{k !}
\end{equation}

7. Why did Watts and Strogatz (WS) come up with a new network model? (**2 pts**) 

Watts and Strogatz observed that some real world networks exhibted properties not present in the random networks, such as having a high clustering coefficient.

Describe the WS model in terms of the network’s characteristic path length and the average clustering coefficient. (**2 pts**) 

It reconstructs the high clustering coefficients and short path lengths of real world networks in creating random networks.

Illustrate how they proposed to generate the model. (**2 pts**)

WS begins with a regular network where each node is connected to $k$ other nodes in the network; i.e., all nodes have the same number of connections/neighbors. Then, with some probability $\rho$, each existing link in the network is rewired. 

*taken from: Legara, Erika Fille. "Complex Network Models." Network Science Lectures. GitHub repository. 2020.*

---

## // End of Part I