In [88]:
# Importing module/library
import csv
import numpy as np
import pandas as pd

In [6]:
#Creating an Array
a = np.array([1, 2, 3, 4])

In [7]:
a

array([1, 2, 3, 4])

In [10]:
a[2]

3

In [11]:
# 1, 2, 3
a[0:3]

array([1, 2, 3])

In [15]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b[0]

array([1, 2, 3])

In [20]:
# Get number 1
b[0, 0]

1

In [24]:
b[:, 0]

array([1, 4, 7])

In [26]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# Get first and second column
b[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
#Change `5` to `10`
b[1, 1] = 10

In [44]:
b

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [50]:
#Sum of the first column
b[:, 0].sum()

12

In [51]:
#Sum of the first and second column
b[:, 0:2].sum()

32

In [52]:
b.sum(axis=0)

array([12, 20, 18])

In [53]:
b.sum(axis=1)

array([ 6, 20, 24])

# Analyzing Wines!

In [57]:
# Importing the dataset
with open('winequality-red.csv', 'r') as file:
    wines = list(csv.reader(file, delimiter=';'))

In [61]:
wines = np.array(wines[1:])

In [62]:
np.shape(wines)

(1599, 12)

In [68]:
wines = wines.astype('float')

In [69]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [72]:
wines_col1 = wines[:, 1]

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"

## What is the average quality of the wines in the collection?

In [78]:
wines[:, -1].mean()

5.6360225140712945

## What is the minimum volatile acidity?

In [79]:
wines[:, 1].min()

0.12

## What's the correlation between volatile acidity and quality?

In [84]:
# 1 line
# np correlation coefficient
vol_ac = wines[:, 1]
qual = wines[:, -1]
np.corrcoef(vol_ac, qual)


array([[ 1.        , -0.39055778],
       [-0.39055778,  1.        ]])

## Is there a correlation between `alcohol content` and `quality`?

In [87]:
# NO RELATIONSHIP

np.corrcoef(wines[:, -1], wines[:, -2])

array([[1.        , 0.47616632],
       [0.47616632, 1.        ]])

In [ ]:
# YES. THERE IS A RELATIONSHIP! If alcohol content increases, so does quality.


In [98]:
with open('titanic.csv', 'r') as file:
    titanic = list(csv.reader(file))

In [100]:
np.array(titanic)

array([['PassengerId', 'Survived', 'Pclass', ..., 'Fare', 'Cabin',
        'Embarked'],
       ['1', '0', '3', ..., '7.25', '', 'S'],
       ['2', '1', '1', ..., '71.2833', 'C85', 'C'],
       ...,
       ['889', '0', '3', ..., '23.45', '', 'S'],
       ['890', '1', '1', ..., '30', 'C148', 'C'],
       ['891', '0', '3', ..., '7.75', '', 'Q']], dtype='<U82')

In [102]:
# Load the titanic dataset
df = pd.read_csv('titanic.csv')

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [105]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## Cleaning the Dataset

In [108]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [114]:
# Removing unnecessary column
del df['PassengerId']

KeyError: 'PassengerId'

In [116]:
# Distribution between male and female - Easy
# Which class had the most survivors - Not easy

Survived  Pclass                                               Name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886         0       2                              Montvila, Rev. Juozas   
887         1       1                       Graham, Miss. Margaret Edith   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"   
889         1       1                              Behr, Mr. Karl Howell   
890         0       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [117]:
# Distribution between male and female - Easy
# value_counts

df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [121]:
# Which class had the most survivors - Not easy
# 1. Survived == 1
# 2. Value counts pclass

# Filtering
df_survived = df[df['Survived'] == 1]


In [123]:
df_survived['Pclass'].value_counts()

1    136
3    119
2     87
Name: Pclass, dtype: int64